[package]
name = "limn"
version = "0.1.7"
authors = ["ManShanko <deathage@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ManShanko/limn"

[profile.release]
opt-level = "s"

[dependencies]
steam_find = { git = "https://github.com/ManShanko/steam_find", rev = "1c951920461a02eab72e2bb92512da541a716e75" }
byteorder = "1.4.3"
leb128 = "0.2.5"
libloading = "0.7.3"
