[package]
name = "limn"
version = "0.7.2"
authors = ["manshanko <manshanko@wartide.net>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/manshanko/limn"

[profile.release]
opt-level = "s"

[dependencies]
steam_find = { git = "https://github.com/manshanko/steam_find", rev = "e0b2c9c1ab94315a10fcdfda63a1e395338d5242" }
byteorder = "1.4.3"
leb128 = "0.2.5"
libloading = "0.7.3"
